import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { poppins } from "@/components/font";
import { DialogProvider } from "@/context/dialogContext";
import CreateNewBoardModal from "@/components/CreateNewBoardModal";
import TaskViewModal from "@/components/TaskViewModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <DialogProvider>
        <html lang="en">
          <body className={poppins.className}>
            {children}
            <TaskViewModal />
            <CreateNewBoardModal />
          </body>
        </html>
      </DialogProvider>
    </ClerkProvider>
  );
}
